source 'https://rubygems.org'

gem 'rails', '~> 3.0'
gem 'coffee-rails'

group :test, :development do
  gem 'mas-development_dependencies',
      path:    '../../',
      require: ['mas/development_dependencies/konacha']
end

group :test do
  gem 'sqlite3'
end
